"""
Database-level inventory integrity.

These tests bypass the service layer entirely and talk to PostgreSQL directly.
The point is that the guarantees hold even if the application is wrong, bypassed
or malicious: a bad stock state must be *unrepresentable*, not merely
unreachable through the happy path.

Covered:
  1.  quantities are exact Decimal/NUMERIC, never binary float
  2.  reserved_quantity cannot be negative
  3.  on_hand_quantity cannot be negative
  4.  reserved cannot exceed on-hand (no backorders)
  5.  available_quantity is generated by the database (on_hand - reserved)
  6.  movement quantity must be positive
  7.  an unknown movement type is rejected
  8.  deltas must agree with the movement type
  9.  manual adjustment requires an actor and a reason
  10. waste requires a reason
  11. the movement ledger is append-only (UPDATE and DELETE both refused)
  12. an order inventory line cannot settle more than it reserved
"""
import uuid
from decimal import Decimal

import pytest
from sqlalchemy import text
from sqlalchemy.exc import DataError, IntegrityError, ProgrammingError

from app.models.ingredient_stock import (
    IngredientStock,
    IngredientStockMovement,
    OrderInventoryLine,
)
from tests.conftest import (
    DEFAULT_STORE_ID,
    _inventory_maintenance,
    cleanup_ingredient,
    make_ingredient,
)

_DB_REJECTS = (IntegrityError, DataError, ProgrammingError)


# ---------------------------------------------------------------------------
# Stock summary
# ---------------------------------------------------------------------------

class TestStockSummaryConstraints:

    def test_quantities_are_decimal_not_float(self, db):
        """Money and mass are exact. 0.1 g added 3 times must be exactly 0.3 g."""
        ing, stock = make_ingredient(db, on_hand=Decimal("0.300"))
        try:
            db.expire_all()
            row = db.query(IngredientStock).filter_by(ingredient_id=ing.id).first()
            assert isinstance(row.on_hand_quantity, Decimal)
            assert isinstance(row.reserved_quantity, Decimal)
            assert isinstance(row.available_quantity, Decimal)
            # The exact-decimal property that float would break.
            assert (
                Decimal("0.100") + Decimal("0.100") + Decimal("0.100")
                == row.on_hand_quantity
            )
        finally:
            cleanup_ingredient(db, ing.id)

    def test_available_is_generated_by_the_database(self, db):
        """available_quantity is never written by the app — the DB derives it."""
        ing, stock = make_ingredient(
            db, on_hand=Decimal("100.000"), reserved=Decimal("30.000")
        )
        try:
            db.expire_all()
            row = db.query(IngredientStock).filter_by(ingredient_id=ing.id).first()
            assert row.available_quantity == Decimal("70.000")

            # Change an input; the generated column follows automatically.
            row.reserved_quantity = Decimal("40.000")
            db.commit()
            db.expire_all()
            row = db.query(IngredientStock).filter_by(ingredient_id=ing.id).first()
            assert row.available_quantity == Decimal("60.000")
        finally:
            cleanup_ingredient(db, ing.id)

    def test_reserved_cannot_be_negative(self, db):
        ing, stock = make_ingredient(db, on_hand=Decimal("10.000"))
        try:
            with pytest.raises(_DB_REJECTS):
                db.execute(
                    text(
                        "UPDATE ingredient_stock SET reserved_quantity = -1 "
                        "WHERE ingredient_id = :i"
                    ),
                    {"i": ing.id},
                )
                db.commit()
            db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)

    def test_on_hand_cannot_be_negative(self, db):
        ing, stock = make_ingredient(db, on_hand=Decimal("10.000"))
        try:
            with pytest.raises(_DB_REJECTS):
                db.execute(
                    text(
                        "UPDATE ingredient_stock SET on_hand_quantity = -1 "
                        "WHERE ingredient_id = :i"
                    ),
                    {"i": ing.id},
                )
                db.commit()
            db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)

    def test_reserved_cannot_exceed_on_hand(self, db):
        """
        Backorders are disabled: the shop cannot promise batter it does not hold.
        """
        ing, stock = make_ingredient(db, on_hand=Decimal("10.000"))
        try:
            with pytest.raises(_DB_REJECTS):
                db.execute(
                    text(
                        "UPDATE ingredient_stock SET reserved_quantity = 10.001 "
                        "WHERE ingredient_id = :i"
                    ),
                    {"i": ing.id},
                )
                db.commit()
            db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)


# ---------------------------------------------------------------------------
# Movement ledger
# ---------------------------------------------------------------------------

def _insert_movement(db, ing_id: int, **overrides) -> None:
    """
    Insert a raw movement row, bypassing the service layer.

    ``store`` defaults to the suite's store, so the constraint tests below read
    unchanged. Passing a different store is how the cross-store tests prove the
    composite foreign keys reject a ledger row that tries to straddle branches —
    and they do it in raw SQL precisely because the point is that the DATABASE
    refuses, not that the service politely declines.
    """
    params = {
        "store_id": DEFAULT_STORE_ID,
        "ingredient_id": ing_id,
        "movement_type": "PURCHASE_RECEIPT",
        "quantity": Decimal("5.000"),
        "delta_on_hand": Decimal("5.000"),
        "delta_reserved": Decimal("0"),
        "unit": "g",
        "reason": "test",
        "actor": None,
        "legacy": False,
    }
    params.update(overrides)
    db.execute(
        text(
            """
            INSERT INTO ingredient_stock_movements (
                store_id, ingredient_id, movement_type, quantity,
                quantity_delta_on_hand, quantity_delta_reserved,
                unit, reason, actor_user_id, legacy_backfill
            ) VALUES (
                :store_id, :ingredient_id, :movement_type, :quantity,
                :delta_on_hand, :delta_reserved,
                :unit, :reason, :actor, :legacy
            )
            """
        ),
        params,
    )
    db.commit()


class TestMovementConstraints:

    def test_quantity_must_be_positive(self, db):
        ing, _ = make_ingredient(db, on_hand=Decimal("10.000"))
        try:
            for bad in (Decimal("0"), Decimal("-5.000")):
                with pytest.raises(_DB_REJECTS):
                    _insert_movement(
                        db, ing.id, quantity=bad,
                        delta_on_hand=bad, actor=None, legacy=True,
                    )
                db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)

    def test_unknown_movement_type_rejected(self, db):
        ing, _ = make_ingredient(db, on_hand=Decimal("10.000"))
        try:
            with pytest.raises(_DB_REJECTS):
                _insert_movement(db, ing.id, movement_type="TELEPORTED", legacy=True)
            db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)

    def test_deltas_must_match_movement_type(self, db):
        """
        A row cannot claim CONSUMPTION while ADDING to physical stock. This is
        what makes an unqualified signed delta impossible.
        """
        ing, _ = make_ingredient(db, on_hand=Decimal("10.000"))
        try:
            with pytest.raises(_DB_REJECTS):
                _insert_movement(
                    db, ing.id,
                    movement_type="CONSUMPTION",
                    quantity=Decimal("5.000"),
                    delta_on_hand=Decimal("5.000"),   # wrong sign
                    delta_reserved=Decimal("-5.000"),
                    actor=None,
                )
            db.rollback()

            # A reservation must not move physical stock.
            with pytest.raises(_DB_REJECTS):
                _insert_movement(
                    db, ing.id,
                    movement_type="RESERVATION_CREATED",
                    quantity=Decimal("5.000"),
                    delta_on_hand=Decimal("-5.000"),  # must be 0
                    delta_reserved=Decimal("5.000"),
                )
            db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)

    def test_manual_adjustment_requires_actor_and_reason(self, db, make_staff):
        ing, _ = make_ingredient(db, on_hand=Decimal("10.000"))
        owner = make_staff("OWNER")
        try:
            # No actor → refused.
            with pytest.raises(_DB_REJECTS):
                _insert_movement(
                    db, ing.id,
                    movement_type="MANUAL_ADJUSTMENT",
                    quantity=Decimal("2.000"),
                    delta_on_hand=Decimal("2.000"),
                    reason="stok sayimi",
                    actor=None,
                )
            db.rollback()

            # No reason → refused.
            with pytest.raises(_DB_REJECTS):
                _insert_movement(
                    db, ing.id,
                    movement_type="MANUAL_ADJUSTMENT",
                    quantity=Decimal("2.000"),
                    delta_on_hand=Decimal("2.000"),
                    reason="   ",           # whitespace is not a reason
                    actor=owner.id,
                )
            db.rollback()

            # Both present → accepted.
            _insert_movement(
                db, ing.id,
                movement_type="MANUAL_ADJUSTMENT",
                quantity=Decimal("2.000"),
                delta_on_hand=Decimal("2.000"),
                reason="stok sayimi",
                actor=owner.id,
            )
            assert db.query(IngredientStockMovement).filter_by(
                ingredient_id=ing.id, movement_type="MANUAL_ADJUSTMENT"
            ).count() == 1
        finally:
            cleanup_ingredient(db, ing.id)

    def test_waste_requires_reason(self, db, make_staff):
        ing, _ = make_ingredient(db, on_hand=Decimal("10.000"))
        owner = make_staff("OWNER")
        try:
            with pytest.raises(_DB_REJECTS):
                _insert_movement(
                    db, ing.id,
                    movement_type="WASTE",
                    quantity=Decimal("2.000"),
                    delta_on_hand=Decimal("-2.000"),
                    reason=None,
                    actor=owner.id,
                )
            db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)

    def test_ledger_is_append_only(self, db, make_staff):
        """
        UPDATE and DELETE on the ledger are both refused. History is corrected
        with a new compensating movement, never by editing the past.
        """
        ing, _ = make_ingredient(db, on_hand=Decimal("10.000"))
        owner = make_staff("OWNER")
        try:
            _insert_movement(
                db, ing.id,
                movement_type="PURCHASE_RECEIPT",
                quantity=Decimal("5.000"),
                delta_on_hand=Decimal("5.000"),
                reason="teslimat",
                actor=owner.id,
            )
            mv = db.query(IngredientStockMovement).filter_by(ingredient_id=ing.id).first()
            assert mv is not None

            with pytest.raises(_DB_REJECTS):
                db.execute(
                    text("UPDATE ingredient_stock_movements SET quantity = 999 WHERE id = :i"),
                    {"i": mv.id},
                )
                db.commit()
            db.rollback()

            with pytest.raises(_DB_REJECTS):
                db.execute(
                    text("DELETE FROM ingredient_stock_movements WHERE id = :i"),
                    {"i": mv.id},
                )
                db.commit()
            db.rollback()

            # Still exactly as written.
            db.expire_all()
            mv = db.query(IngredientStockMovement).filter_by(ingredient_id=ing.id).first()
            assert mv.quantity == Decimal("5.000")
        finally:
            cleanup_ingredient(db, ing.id)


# ---------------------------------------------------------------------------
# Order inventory lines
# ---------------------------------------------------------------------------

class TestOrderInventoryLineConstraints:

    def test_settled_cannot_exceed_reserved(self, db, client):
        """
        consumed + released <= reserved. This single constraint is what makes
        double-consumption and consume-then-release structurally impossible,
        even for a caller that bypasses the service.
        """
        from tests.conftest import order_payload

        ing, _ = make_ingredient(
            db, on_hand=Decimal("100.000"), standard_quantity=Decimal("10.00")
        )
        try:
            payload, headers = order_payload(ing.id, idem_key=uuid.uuid4().hex)
            r = client.post("/public/orders/", json=payload, headers=headers)
            assert r.status_code == 200

            line = db.query(OrderInventoryLine).filter_by(ingredient_id=ing.id).first()
            assert line is not None
            assert line.reserved_quantity == Decimal("10.000")

            # Consume more than was ever reserved.
            with pytest.raises(_DB_REJECTS):
                db.execute(
                    text(
                        "UPDATE order_inventory_lines SET consumed_quantity = 10.001 "
                        "WHERE id = :i"
                    ),
                    {"i": line.id},
                )
                db.commit()
            db.rollback()

            # Consume all of it AND release all of it.
            with pytest.raises(_DB_REJECTS):
                db.execute(
                    text(
                        "UPDATE order_inventory_lines "
                        "SET consumed_quantity = 10, released_quantity = 10 "
                        "WHERE id = :i"
                    ),
                    {"i": line.id},
                )
                db.commit()
            db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)

    def test_quantities_cannot_be_negative(self, db, client):
        from tests.conftest import order_payload

        ing, _ = make_ingredient(
            db, on_hand=Decimal("100.000"), standard_quantity=Decimal("10.00")
        )
        try:
            payload, headers = order_payload(ing.id, idem_key=uuid.uuid4().hex)
            client.post("/public/orders/", json=payload, headers=headers)
            line = db.query(OrderInventoryLine).filter_by(ingredient_id=ing.id).first()

            for column in ("consumed_quantity", "released_quantity", "waste_quantity"):
                with pytest.raises(_DB_REJECTS):
                    db.execute(
                        text(
                            f"UPDATE order_inventory_lines SET {column} = -1 WHERE id = :i"
                        ),
                        {"i": line.id},
                    )
                    db.commit()
                db.rollback()
        finally:
            cleanup_ingredient(db, ing.id)
