/**
 * Turkish display labels for the enum values the API sends.
 *
 * The API speaks English enums — TRANSFER_OUT, stock_risk, IN_PREP — and that
 * stays the wire contract: never translated, never renamed, and every comparison
 * in this app is still made against the English value. This module is the one
 * place where those values become manager-readable, so that a raw
 * `PURCHASE_RECEIPT` can never reach the screen.
 *
 * Look values up through the helpers, not by indexing the records directly —
 * the helpers decide what an unknown value renders as.
 */

/**
 * Inventory movement types (`movement_type` on a stock movement).
 *
 * Two pairs here are easy to confuse and expensive to get wrong, so they are
 * named for what physically happened, not for the arithmetic sign:
 *   WASTE            — stock binned. Money lost.
 *   TRANSFER_OUT     — stock shipped to another branch. Money not lost.
 *   PURCHASE_RECEIPT — stock bought from a supplier.
 *   TRANSFER_IN      — stock received from another branch. Nothing was bought.
 * Labelling a transfer as "Fire" or "Mal kabul" would quietly corrupt the
 * owner's read of both waste and purchasing.
 *
 * A third distinction, and the same kind of mistake:
 *   MANUAL_ADJUSTMENT      — "Manuel düzeltme". Someone knew a figure was wrong and
 *                            corrected it.
 *   STOCK_COUNT_ADJUSTMENT — "Sayım düzeltmesi". Someone COUNTED the shelf and the
 *                            system was made to agree with what they found.
 * They are different events with different evidence behind them. Showing a counted
 * discrepancy as "Manuel düzeltme" would hide shrinkage inside a label that means
 * "we decided to change this number".
 */
export const MOVEMENT_TYPE_LABEL: Record<string, string> = {
  RESERVATION_CREATED: "Stok ayrıldı",
  RESERVATION_RELEASED: "Ayrılan stok bırakıldı",
  CONSUMPTION: "Tüketim",
  WASTE: "Fire",
  RETURNED: "İade edilen stok",
  MANUAL_ADJUSTMENT: "Manuel düzeltme",
  PURCHASE_RECEIPT: "Mal kabul",
  TRANSFER_OUT: "Şubeden çıkış",
  TRANSFER_IN: "Şubeye giriş",
  STOCK_COUNT_ADJUSTMENT: "Sayım düzeltmesi",
};

/** Kitchen preparation state of an order. */
export const ORDER_STATUS_LABEL: Record<string, string> = {
  NEW: "Bekliyor",
  IN_PREP: "Hazırlanıyor",
  READY: "Hazır",
  DELIVERED: "Teslim edildi",
  CANCELLED: "İptal edildi",
};

/** Decision signal type, as generated by the backend decision engine. */
export const DECISION_TYPE_LABEL: Record<string, string> = {
  stock_risk: "Stok riski",
  demand_spike: "Talep artışı",
  slow_moving: "Yavaş hareket",
  sla_risk: "Hazırlık süresi riski",
  revenue_anomaly: "Ciro sapması",
  metric_combo_health: "Kombinasyon performansı",
  metric_upsell_visibility: "Öneri görünürlüğü",
  metric_owner_engagement: "Uyarı takibi",
  metric_kitchen_performance: "Mutfak performansı",
};

/** Lifecycle state of a decision the owner is working through. */
export const DECISION_STATUS_LABEL: Record<string, string> = {
  pending: "Bekliyor",
  acknowledged: "Görüldü",
  completed: "Tamamlandı",
  dismissed: "Kapatıldı",
};

/** How well a completed decision actually resolved the underlying problem. */
export const RESOLUTION_QUALITY_LABEL: Record<string, string> = {
  good: "Sorun çözüldü",
  partial: "Kısmen çözüldü",
  failed: "Çözülemedi",
};

/** Severity of a decision or a stock warning. */
export const SEVERITY_LABEL: Record<string, string> = {
  high: "Yüksek",
  medium: "Orta",
  low: "Düşük",
};

/** Current kitchen load band. */
export const LOAD_LEVEL_LABEL: Record<string, string> = {
  low: "Sakin",
  medium: "Normal",
  high: "Yoğun",
};

/** Per-order SLA severity shown on the kitchen board. */
export const SLA_SEVERITY_LABEL: Record<string, string> = {
  ok: "Zamanında",
  warning: "Süre doluyor",
  critical: "Süre aşıldı",
};

/** Trustworthiness of a computed metric. */
export const DATA_QUALITY_LABEL: Record<string, string> = {
  valid: "Geçerli",
  low_sample: "az veri",
  no_data: "veri yok",
  unreliable: "güvenilmez",
};

/** Operational mode the system has put itself into. */
export const OPERATIONAL_MODE_LABEL: Record<string, string> = {
  normal: "Normal",
  boost_combos: "Kombinasyon görünürlüğü düşük",
  high_kitchen_load: "Mutfak yoğun",
  sla_critical: "Mutfak kritik",
};

/**
 * Look a wire value up in one of the maps above.
 *
 * An unknown value renders as `fallback`, never as the raw enum. A manager who
 * sees "Bilinmiyor" knows the row is odd and can ask; one who sees
 * "TRANSFER_OUT_PENDING" has been handed an internal identifier to interpret.
 */
export function labelFor(
  map: Record<string, string>,
  value: string | null | undefined,
  fallback = "Bilinmiyor",
): string {
  if (!value) return fallback;
  return map[value] ?? fallback;
}

export const movementTypeLabel = (v: string | null | undefined) =>
  labelFor(MOVEMENT_TYPE_LABEL, v, "Diğer stok hareketi");

export const orderStatusLabel = (v: string | null | undefined) =>
  labelFor(ORDER_STATUS_LABEL, v);

export const decisionTypeLabel = (v: string | null | undefined) =>
  labelFor(DECISION_TYPE_LABEL, v, "Uyarı");

export const decisionStatusLabel = (v: string | null | undefined) =>
  labelFor(DECISION_STATUS_LABEL, v);

export const resolutionQualityLabel = (v: string | null | undefined) =>
  labelFor(RESOLUTION_QUALITY_LABEL, v);

export const severityLabel = (v: string | null | undefined) =>
  labelFor(SEVERITY_LABEL, v);

export const loadLevelLabel = (v: string | null | undefined) =>
  labelFor(LOAD_LEVEL_LABEL, v);

export const slaSeverityLabel = (v: string | null | undefined) =>
  labelFor(SLA_SEVERITY_LABEL, v);

export const dataQualityLabel = (v: string | null | undefined) =>
  labelFor(DATA_QUALITY_LABEL, v);
